import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Dblog</title>
        <meta name="description" content="Generated by Dinocan" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-neutral-900">
        <div className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
          <h1 className="text-8xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-palette-200 to-palette-500">Welcome to DShop!</h1>
        </div>
      </main>
    </>
  );
};

export default Home;