
name: 'Release'
on: [push]

jobs:
  release:
    name: Test repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use PnPm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Install NPM Dependencies
        run: pnpm install
      
      - name: Check errors
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON }}
          NEXT_PUBLIC_DEFAULT_SHOP_NAME: ${{ secrets.NEXT_PUBLIC_DEFAULT_SHOP_NAME }}
        run: pnpm check

      - name: Build package
        run: pnpm build
